// <auto-generated />
using BeerCollection.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerCollection.API.Migrations
{
    [DbContext(typeof(BeerContext))]
    partial class BeerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerCollection.API.Entities.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tuborg",
                            Rating = 1.0,
                            Type = "Strong"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kingfisher",
                            Rating = 1.0,
                            Type = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carlsberg",
                            Rating = 1.0,
                            Type = "Elephant"
                        });
                });

            modelBuilder.Entity("BeerCollection.API.Entities.BeerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("BeerRatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeerId = 1,
                            Description = "Delicious",
                            Rate = 3
                        },
                        new
                        {
                            Id = 2,
                            BeerId = 1,
                            Description = "Special",
                            Rate = 5
                        },
                        new
                        {
                            Id = 3,
                            BeerId = 2,
                            Description = "Delicious",
                            Rate = 3
                        },
                        new
                        {
                            Id = 4,
                            BeerId = 2,
                            Description = "Delicious",
                            Rate = 5
                        },
                        new
                        {
                            Id = 5,
                            BeerId = 3,
                            Description = "Delicious",
                            Rate = 3
                        },
                        new
                        {
                            Id = 6,
                            BeerId = 3,
                            Description = "Delicious",
                            Rate = 3
                        });
                });

            modelBuilder.Entity("BeerCollection.API.Entities.BeerRating", b =>
                {
                    b.HasOne("BeerCollection.API.Entities.Beer", "Beer")
                        .WithMany("BeerRatings")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("BeerCollection.API.Entities.Beer", b =>
                {
                    b.Navigation("BeerRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
